SessionController
java-park-mail-ru/air-drones-09-2016 pull request #1
Opened 2016-09-25 14:01 UTC by DmitryZagr

Добрый день!
Ориентировался на API с фронтенда, которое Вы показывали.
Я не очень понимаю, как сделать метод получения информации о пользователе информации через GET запрос. вот пример: 
`@RequestMapping(path = "/user", method = RequestMethod.GET)
    public ResponseEntity getUser(@RequestParam(name = "login") String login) `
Если передавать login в url-стороке, то так можно получить информацию о любом юзере. 

В API с фронтенда при выполнении запроса вида /session, который выполняет логаут,  где RequestMethod.DELETE, не передаются никакие параметры. Как мне узнать тогда узнать id-сесии? В этот объект HttpSession httpSession сама прилетит нужная мне сессия с клиента, если я вот так объявлю метод ? 
`@RequestMapping(path = "/session", method = RequestMethod.DELETE)
    public ResponseEntity sigOut(HttpSession httpSession) `

2016-09-25 14:38 UTC, KSolovyev commented
Да, прилетит. При этом надо учитывать, что jetty устанвливает сессию, если она нет или истекла. Поэтому случай, когда к вам на любой адрес стучит пользователь с неизвестной сессией, может происходит довольно таки часто.
В идеальном случае на логаут постучит пользователь с id сессии точно таким же, какой был при логине. Этой информации достаточно для любых операций с пользователем и сессией.

2016-09-25 14:51 UTC, KSolovyev commented
А у вас есть API  на свагере? Если нет я подожду пока не появится. Без него сложно понять правильно ли написаны методы

2016-09-25 14:55 UTC, KSolovyev commented
А еще нужно добавить .gitignore и удалить все те файлы, которые не нужны для разработки и сборки. В частности папку /target/ со всем содержимым

2016-09-25 14:58 UTC, DmitryZagr commented
Спасибо! 
API на свагере пока нет, скоро напишем. 
гит игнор поправлю

2016-09-29 16:01 UTC, d-frolov reviewed
Ну и вообще прогоните пожалуйста инспекции с правильным профилем и исправьте все проблемы

2016-09-29 16:01 UTC, d-frolov commented on L1.3.iml
> +<?xml version="1.0" encoding="UTF-8"?>
удалите пожалуйста iml файлы, у нас же структура проекта определяется по pom.xml

2016-09-29 16:01 UTC, d-frolov commented on target/classes/application.properties
> +banner.location=file:src/main/resources/banner.txt
убрать папку target и добавить в игнор

2016-09-29 16:01 UTC, d-frolov commented on pom.xml
> +    <artifactId>L1.3</artifactId>
поменяйте arifactId  на название вашего проекта

2016-09-29 16:01 UTC, d-frolov commented on tp_java_new.xml
> +<?xml version="1.0" encoding="UTF-8"?>
выкиньте этот файл из проекта

2016-09-29 16:01 UTC, d-frolov commented on tp_java_new.xml
> +<?xml version="1.0" encoding="UTF-8"?>
в смысле пусть у вас будет локально правильная версия инспекций, но меня ее не надо и не надо ее заливать в проект

2016-09-29 16:01 UTC, d-frolov commented on src/main/java/ru/mail/park/services/AccountService.java
> +package ru.mail.park.services;
Разделите пожалуйста сервисы на интерфейс и реализация

Это очень будет полезно для структурирования вашего проекта, для тестирования, для замены имплементации под БД и т.д.

2016-09-29 16:24 UTC, d-frolov commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    private static final class RegistrationRequest {
Думаю лучше вынести все реквесты-респонсы в отдельные классы в отдельную папку

2016-10-02 06:39 UTC, DmitryZagr commented
Инспекция помечает некоторые нужные мне методы, как неиспользуемые

2016-10-02 08:04 UTC, DmitryZagr commented
api в файлике ReadMe

2016-10-02 08:40 UTC, KSolovyev commented
А зачем нужен метод GET /session/?

2016-10-02 08:46 UTC, DmitryZagr commented
в исходной документации с фронтенда он был, мы решили его у себя оставить. Я пока не знаю, как этот метод может пригодиться ребятам с фронта:)  Если он не нужен будет, то удалим

2016-10-02 10:38 UTC, KSolovyev commented
В спецификации не должно быть сессии. Она передается через Cookie и ее ипользование подразумевается. Убирайте ее отовсюду. Посмотрите как сделано в
http://petstore.swagger.io/#!/user/updateUser
Там тоже есть регистрация и авторизация

Кроме того в вашей спеке не понятно, что отсылать. При логине мне нужно послать пользователя? С email'ом?
А в информации о пользователе я получу пароль?

Если вы не знаете как что-то использовать, то удаляйте. Появится необходимость - добавите

2016-10-02 11:35 UTC, DmitryZagr commented
для логина достаточно послать email и password.

2016-10-02 11:37 UTC, DmitryZagr commented
теперь в информации о пользователе прилетит только логин и email 
передам парням с фронтенда, чтоб переделали спецификацию

2016-10-02 11:41 UTC, DmitryZagr commented
я неправильно написал. у нас нет логина, есть - username. Это поле неуникальное.
email - уникальное поле. Логин происходит по email и password

2016-10-02 19:01 UTC, KSolovyev commented
Надо дождаться, когда будет готова спецификация

2016-10-04 16:26 UTC, DmitryZagr commented
https://air-drone-front.herokuapp.com/api/ 
вот готовое api 
правда, почему-то опять получилось разночтение небольшое. Чтобы выполнить запрос /user методом get, не надо передавать никакие параметры.

2016-10-04 21:27 UTC, DmitryZagr commented
поправил API

2016-10-04 23:05 UTC, KSolovyev requested changes

2016-10-04 23:05 UTC, KSolovyev commented on pom.xml
> +    <version>1.0-SNAPSHOT</version>
Назовите проект по-другому. L1.3 - это пример для 3-й лекции. Версию тоже нужно поставить свою

2016-10-04 23:05 UTC, KSolovyev commented on pom.xml
> +        <version>1.4.0.RELEASE</version>
Есть более свежая версия

2016-10-04 23:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +        System.err.println(sessionId);
данная строка выводит в id сессии в стандартный поток ошибок вашего процесса. Это точно то, что вы хотели? Скорее всего нет. Тут нужно воспользоваться уже подключенным в проект логером log4j. У экземпляра данного логгера есть метод debug(), которым и надо пользоваться в таких случаях. На мой взгляд здесь достаточно было использовать отладчик. Поверьте это удобнее

2016-10-04 23:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +//    Метод получения информации о пользователе
Уберите коммент. Если название метода само за себя не говорит, что оно делает, то лучше придумайте другое

2016-10-04 23:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +//    Метод удаления пользователя
комментарий не нужен

2016-10-04 23:05 UTC, KSolovyev commented on README.md
> +Dmitriy Frolov https://github.com/d-frolov
ЭЙ! ЭТО МОЕ README! 
А если серьезно, то этот текст будет у вас на главной страничке в репозитории.
Здесь же должна быть ссылка на swagger

2016-10-04 23:05 UTC, KSolovyev commented on target/classes/banner.txt
> +
Не хотите эмблемку поменять?

2016-10-04 23:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/model/UserProfile.java
> +        this.id = ID_GENETATOR.getAndAdd(1);
давайте заиспользуем метод getAndIncrement()

2016-10-04 23:05 UTC, KSolovyev commented on README.md
> +Dmitriy Frolov https://github.com/d-frolov
Нужно написать свое README. Кратко опишите проект, напишите список участников, можно добавить ссылку на технопарк

2016-10-04 23:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/RegistrationController.java
> +    //    Метод создания пользователя
Нужно убрать такие комментарии. Метод сам по себе говорит, что он делает, поэтому такой комментарий бесполезен

2016-10-04 23:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/RegistrationController.java
> +    //    Метод создания пользователя
У всех остальных методов нужно так же их поубирать

2016-10-04 23:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +public final class RegistraionReqResp {
Предлагаю назвать класс Registration и сложить в отдельный пакет. Например api

2016-10-04 23:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +    public static final class UserReqResp {
Это уже не относится к регистрации, поэтому надо вынести из этого класса

2016-10-04 23:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +    public static final class PutUserRequest {
Аналогично. Надо вынести

2016-10-04 23:05 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +    public static final class GetUserResponce {
Этот тоже выносим

2016-10-04 23:05 UTC, KSolovyev commented on src/main/resources/banner.txt
> +
Баннер не хотите на свой поменять? =)

2016-10-05 09:14 UTC, DmitryZagr commented on pom.xml
> +    <version>1.0-SNAPSHOT</version>
Я может быть как-то криво сделал pull request, но это очень старая версия, первые коммиты

2016-10-05 09:15 UTC, DmitryZagr commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +        System.err.println(sessionId);
и этого тоже нет в текущей версии)

2016-10-05 09:16 UTC, DmitryZagr commented on README.md
> +Dmitriy Frolov https://github.com/d-frolov
в текущем README есть ссылка на api. Остальное поправлю

2016-10-05 09:22 UTC, DmitryZagr commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +    public static final class GetUserResponce {
вы хотите, чтобы я вынес GetUserResponce и аналогичные вложенные классы  в отдельные классы?
а зачем? я сгруппировал сущности ответов для класса Reqistration в отдельном классе контейнере , чтобы не плодить много маленьких классов. Разве так не удобнее, чем держать эти сущности в самостоятельных классах?

2016-10-05 09:24 UTC, DmitryZagr commented on target/classes/banner.txt
> +
чашечка кофе уже не в моде?)

2016-10-05 09:26 UTC, DmitryZagr commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +    public static final class GetUserResponce {
тогда мне может просто переименовать класс-контейнер из ReqistraionReqResp в что-то вроде WorkWithUser. и оставить все маленькие подклассы в нем

2016-10-05 09:34 UTC, DmitryZagr commented on pom.xml
> +    <version>1.0-SNAPSHOT</version>
а да, все коммиты из ветки разработки попали в ветку master

2016-10-05 10:50 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +    public static final class GetUserResponce {
Можно групировать вместе запрос-ответ. Это действительно имеет смысл. Просто так раздувать класс не стоит. Лучше сделайте отдельный пакет

2016-10-05 10:57 UTC, KSolovyev commented on target/classes/banner.txt
> +
Я понял. Надо было логотип mail.Ru поставить, чтобы его сразу хотелось убрать =)

2016-10-05 10:58 UTC, KSolovyev commented on README.md
> +Dmitriy Frolov https://github.com/d-frolov
Правьте

2016-10-06 08:54 UTC, DmitryZagr commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +    public static final class GetUserResponce {
поправил

2016-10-06 08:54 UTC, DmitryZagr commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +    public static final class PutUserRequest {
поправил

2016-10-06 08:54 UTC, DmitryZagr commented on src/main/java/ru/mail/park/model/UserProfile.java
> +        this.id = ID_GENETATOR.getAndAdd(1);
поправил

2016-10-07 09:27 UTC, DmitryZagr commented on target/classes/application.properties
> +banner.location=file:src/main/resources/banner.txt
убрал

2016-10-07 09:27 UTC, DmitryZagr commented on tp_java_new.xml
> +<?xml version="1.0" encoding="UTF-8"?>
убрал

2016-10-07 09:27 UTC, DmitryZagr commented on src/main/java/ru/mail/park/services/AccountService.java
> +package ru.mail.park.services;
сделал

2016-10-07 09:27 UTC, DmitryZagr commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +    private static final class RegistrationRequest {
сделал

2016-10-07 09:28 UTC, DmitryZagr commented on pom.xml
> +    <artifactId>L1.3</artifactId>
исправил

2016-10-07 09:28 UTC, DmitryZagr commented on L1.3.iml
> +<?xml version="1.0" encoding="UTF-8"?>
удалил

2016-10-07 09:28 UTC, DmitryZagr commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +//    Метод получения информации о пользователе
убрал

2016-10-07 09:28 UTC, DmitryZagr commented on src/main/java/ru/mail/park/main/RegistrationController.java
> +//    Метод удаления пользователя
убрал

2016-10-07 09:29 UTC, DmitryZagr commented on src/main/java/ru/mail/park/controllers/RegistrationController.java
> +    //    Метод создания пользователя
убрал

2016-10-07 09:29 UTC, DmitryZagr commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +public final class RegistraionReqResp {
переделал структкру

2016-10-07 09:29 UTC, DmitryZagr commented on src/main/java/ru/mail/park/controllers/entities/RegistraionReqResp.java
> +    public static final class UserReqResp {
поправил

2016-10-08 23:15 UTC, KSolovyev requested changes

2016-10-08 23:15 UTC, KSolovyev commented on src/main/java/ru/mail/park/service/implementation/SessionServiceImpl.java
> +    private static final Map<String, String> COOKIE_TO_EMAIL = new HashMap<>();
static здесь не нужен. Считайте, что сервис - это почти сингл тон

2016-10-08 23:15 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/UserController.java
> +            else ResponseEntity.status(HttpStatus.BAD_REQUEST).body("{}");
Что-то у вас здесь треш творится, очень сложно читать. Скобочки что ли расставьте

2016-10-08 23:15 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/UserController.java
> +    public ResponseEntity deleteUser(@RequestBody @Valid  DeleteUserRequest body,
в DeleteUserRequest нет никаких валидаторов, может стоит убрать?

2016-10-14 21:17 UTC, d-frolov commented
Други мои, ну вы, для приличия, по моим вопросам поправки сделайте пожалуйста. Мне же надо вам реквест закрыть.

2016-10-22 10:28 UTC, DmitryZagr commented
так я же давно поправил, d-frolov

2016-10-22 10:44 UTC, DmitryZagr commented on src/main/java/ru/mail/park/controllers/UserController.java
> +            else ResponseEntity.status(HttpStatus.BAD_REQUEST).body("{}");
исправил

2016-10-22 10:44 UTC, DmitryZagr commented on src/main/java/ru/mail/park/controllers/UserController.java
> +    public ResponseEntity deleteUser(@RequestBody @Valid  DeleteUserRequest body,
убрал

2016-10-22 10:44 UTC, DmitryZagr commented on src/main/java/ru/mail/park/service/implementation/SessionServiceImpl.java
> +    private static final Map<String, String> COOKIE_TO_EMAIL = new HashMap<>();
убрал

2016-10-22 12:54 UTC, merged

2016-10-22 12:56 UTC, d-frolov commented
Я вижу, что вы забили на мои просьбы. Реквест закрыл. Делайте второй рк

2016-10-22 13:00 UTC, DmitryZagr commented
Почему я забил? я же поправил все кроме инспекций. Мы с isopov сошлись на том, что они не совсем корректные. В чем проблемы остались?

2016-10-22 13:03 UTC, DmitryZagr commented
я удалил папку target, разделили сервисы на интерфейсы и реализацию, удалили imi файлы, сменил название проекта, удалил файл инспекций из гита

2016-10-22 13:07 UTC, DmitryZagr commented
ну и вытащил все вложенные классы в пакет api, как мы с Вами обсуждали

2016-10-22 13:12 UTC, DmitryZagr commented
скажите, пожалуйста, что не так. Не хотелось бы перетаскивать какие-либо косяки во второй рк.

2016-10-22 13:55 UTC, DmitryZagr commented
Если в этих инспекциях класс явно не инстанцировать, то он помечается, как unused. Это относится и к конструкторам, я их явно не использую, но их использует спринг. Из-за этого возникает большая часть ошибок в инспекции. Еще инспекция ругается на gitignore.

2016-10-22 17:03 UTC, d-frolov commented
Ну почитайте мои комментарии к этому реквесту

2016-10-22 17:05 UTC, d-frolov commented
Ну вот это  

Это C++ стиль так называть интерфейсы через букву I
Обычно в Java принято немного другой подход 

А зачем вы передаете в качестве параметров конструктора имплементации, а не интерфейсы?
Теряется гибкость

2016-10-22 17:06 UTC, d-frolov commented
По названиям, вкусовщина, конечно. Но в Java так принято. А с имплементациями это просто плохой пример кода

2016-10-23 22:39 UTC, DmitryZagr commented
Я ведь исправил Ваши замечания, которые Вы написали выше. Во втором реквесте изменил названия с I на Abstract.  Просто isopov тоже пишет в своих примерах c I.