Второе РК
java-park-mail-ru/air-drones-09-2016 pull request #3
Opened 2016-10-23 22:41 UTC by DmitryZagr

2016-10-25 14:29 UTC, KSolovyev requested changes
Еще нужно добавить версионирование схемы. Те sql инструкции, которыми вы создавали базу. В идеале вообще перейти на flyway. Это вам поможет сэкономить кучу сил

2016-10-25 14:29 UTC, KSolovyev commented on pom.xml
> +            <!--<exclusions>-->
убирайте закомментированный код

2016-10-25 14:29 UTC, KSolovyev commented on pom.xml
> +        </dependency>
так postgre или MySQL?

2016-10-25 14:29 UTC, KSolovyev commented on src/test/java/ru/mail/park/service/implementation/AccountServiceTest.java
> +    private DataSource dataSource;
У вас тесты исполняются на боевой базе. Так делать нельзя: база должна быть тестовой

2016-10-25 14:29 UTC, KSolovyev commented on src/main/java/ru/mail/park/model/rating/Rating.java
> +public class Rating {
Предполагается, что у пользователя будет несколько записей "рейтинг"? За каждый матч что ли?

2016-10-25 14:29 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/UserController.java
> +            sessionService.signOut(httpSession.getId());
Во-первых код кидает только одно исключение, и остальные здесь не нужны. Во вторых логика не должна работать на исключениях. Тут нужно все поменять на условные переходы, ведь все эти случаи вы можете проверить. Исключение нужно кидать, когда вы проверили, а база данных вам кидает ConstraintViolationException. Обычно это означает гонку. В этом случае вы действительно ничего сделать не можете. А в обычных условиях нужно просто делать проверку.

2016-10-25 14:29 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/UserController.java
> +            sessionService.signOut(httpSession.getId());
И остальные методы тоже надо переписать

2016-10-25 14:29 UTC, KSolovyev commented on src/main/java/ru/mail/park/service/implementation/SessionService.java
> +            throw new NotLoggedInException();
А в чем смысл этих исключений? Я думаю в первой функции надо возвращать true\false, во второй, если не найден пользователь, то возвращать null, а в третьей, если сессии нет, то вообще ничего не делать.

2016-10-25 14:48 UTC, DmitryZagr commented on pom.xml
> +        </dependency>
для локальной разработки использую mySql. На хероку только Postgres не просит ввести номер кредитки

2016-10-25 15:02 UTC, DmitryZagr commented on src/test/java/ru/mail/park/service/implementation/AccountServiceTest.java
> +    private DataSource dataSource;
Добавил тестовую базу

2016-10-25 15:05 UTC, DmitryZagr commented on src/main/java/ru/mail/park/model/rating/Rating.java
> +public class Rating {
это общий рейтинг. Связь один к одному должна быть. Через HashMap сделать?

2016-10-25 15:08 UTC, DmitryZagr commented on src/main/java/ru/mail/park/service/implementation/SessionService.java
> +            throw new NotLoggedInException();
Для логирования, как мне кажется, будет удобно. Исключения дают информацию об ошибках детальную, да и на фронтенд можно ошибки кидать: код HTTP ошибки + текстовое сообщение из-за чего она возникла(дают исключения).

2016-10-25 19:51 UTC, KSolovyev commented on src/main/java/ru/mail/park/model/rating/Rating.java
> +public class Rating {
Нет, зачем? Просто в пользователя добавьте поле

2016-10-25 19:52 UTC, KSolovyev commented on src/main/java/ru/mail/park/service/implementation/SessionService.java
> +            throw new NotLoggedInException();
Так это не ошибка. Просто пользователь не залогинен

2016-10-26 00:44 UTC, DmitryZagr commented on src/main/java/ru/mail/park/model/rating/Rating.java
> +public class Rating {
поправил

2016-10-26 00:44 UTC, DmitryZagr commented on src/main/java/ru/mail/park/controllers/UserController.java
> +            sessionService.signOut(httpSession.getId());
поправил и добавил инструкции sql

2016-10-26 07:27 UTC, KSolovyev commented on pom.xml
> +        </dependency>
У меня есть карточка, номер которой я даю всем студентам. Ну или поставьте локально postgres

2016-10-26 16:44 UTC, DmitryZagr commented on pom.xml
> +        </dependency>
уже перешел на постгрес, дальше работать в нем буду. В следующем комите уберу зависимости

2016-10-26 18:29 UTC, KSolovyev commented
У вас есть класс AbstractResponse - абсолютно бесполезный класс.  У него нет никакого интерфейса, нет никакой реализации. Только путает такое наследование

2016-10-26 18:31 UTC, KSolovyev commented
И AbstractRequest - такой же

2016-10-26 18:33 UTC, DmitryZagr commented
Странно, я его удалил вчера как раз AbstractRequest.
В остальном нормально или еще что-то добавить/доработать?

2016-10-26 19:04 UTC, KSolovyev commented
из  pom.xml уберите mysql driver раз уж не используете его

2016-10-27 01:08 UTC, DmitryZagr commented
поправил

2016-10-30 15:30 UTC, merged